### Step 1:Importing Libraries

In [9]:
import pandas as pd 
import numpy as np
!pip install pymysql    #Work on connect to mysql

Requirement already satisfied: pymysql in c:\users\admin\anaconda3\lib\site-packages (1.2.0)

### Step 2: Load Dataset

In [14]:
df = pd.read_excel(r"C:\Users\ADMIN\Downloads\End to End Project\End to End Project\Ecommerce_Unclean_Project.xlsx")

### 3: Explore the dataset

In [15]:
# View First 5 Records

df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [17]:
#Statistical Summary
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [18]:
# Dataset Shape
df.shape

(524, 15)

### Step 4: Check Missing Values

In [19]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

### Step 5: Check Duplicate Records

In [58]:
df.duplicated().sum()

np.int64(0)

In [21]:
# Ramove Duplicate Records

df = df.drop_duplicates()

In [22]:
df.duplicated().sum()

np.int64(0)

### 6: Replace Invalid Values

In [23]:
# Replace common invalid values with NaN
# N/A,NULL Replace with NaN

df.replace(['N/A','NULL',''],np.nan,inplace=True)

In [24]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

### Step 7: Remove Extra Spaces`

In [25]:
df = df.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

### Step 8: Standardize Text Format

In [26]:
# Convert text into Proper Case.

df['Customer_Name'] = df['Customer_Name'].str.title()

df['City'] = df['City'].str.title()

df['State'] = df['State'].str.title()

### Step :9 Validate Email Addresses

In [27]:
# Keep only vaild email records.

df = df[df['Email'].str.contains('@',na=False)]

### Step 10: Convert Date Columns

In [29]:
df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')
df['Delivery_Date']=pd.to_datetime(df['Delivery_Date'],errors='coerce')

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_29164\3847401706.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')

### Step 11: Convert Numeric Columns

In [30]:
cols = ['Qty','Unit_Price','Discount']

for c in cols:
    df[c] = pd.to_numeric(df[c],errors='coerce')

### Step 12: Remove Invalid Quantity

In [31]:
# Remove records having negative or zero quantity.

df = df[df['Qty']>0]

### Step 13: Fill Missing Values

In [32]:
df['Discount'] = df['Discount'].fillna(0)  #"If the discount value is null, replace it with 0."

df['Phone'] = df ['Phone'].fillna ('Unknown') #"If the value is N/A, replace it with 0."

df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

### Step 14: Feature Engineering

In [33]:
# Add Total Sales Column.

df['Sales']=df['Qty']*df['Unit_Price']

In [34]:
# Add Net Amount Columns

df['Net_Amount']=df['Sales']-(df['Sales']*df['Discount']/100)

In [35]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-09-02,24995.0,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-08-05,5997.0,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0,2998.0
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-10,NaN,NaN
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0,2997.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,0.0,COD,Cancelled,2025-09-03,2997.0,2997.0

In [49]:
# Profit (Example: 20%)
df['Profit']=df['Net_Amount'] # Adding again one columns

In [37]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.0,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,0.0,Card,Pending,2025-09-02,24995.0,24995.0,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,0.0,COD,Returned,2025-08-05,5997.0,5997.0,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,0.0,Wallet,Cancelled,2025-02-10,1497.0,1497.0,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0,39996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.0,39996.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0,2998.0,2998.0
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,0.0,NetBanking,Delivered,2025-04-10,NaN,NaN,NaN
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0,2997.0,2997.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,0.0,COD,Cancelled,2025-09-03,2997.0,2997.0,2997.0

In [38]:
# Order Manth
df['Month'] = df['Order_Date'].dt.month_name() 
# Add Month column.

In [39]:
# Order Year 
df['Year'] = df['Order_Date'].dt.year
# Add Year Column.

In [41]:
# Weekday
# Add Week Column.
df['Weekday']=df['Order_Date'].dt.day_name()

## Step 15: EDA

### Sales by Category

In [67]:
df.groupby('Category')['Net_Amount'].sum().sort_values(ascending=False)

Category
Electronics    1406096.0
Fashion         960973.0
Furniture       718109.0
Home            641898.0
Name: Net_Amount, dtype: float64

### Sales By Products

In [68]:
df.groupby('Product')['Net_Amount'].sum().sort_values(ascending=False)

Product
Laptop    726101.0
Chair     718109.0
Mouse     679995.0
Bottle    641898.0
Watch     548440.0
Shoes     412533.0
Name: Net_Amount, dtype: float64

### Sales By City

In [69]:
df.groupby('City')['Net_Amount'].sum().sort_values(ascending=False)

City
Pune         841279.0
Bengaluru    827695.0
Delhi        578816.0
Lucknow      548942.0
Mumbai       518500.0
Jaipur       411844.0
Name: Net_Amount, dtype: float64

### Sales by Payment Mode

In [70]:
df.groupby('Payment_Mode')['Net_Amount'].sum().sort_values(ascending=False)

Payment_Mode
NetBanking    809076.0
Wallet        801442.0
COD           778638.0
UPI           678817.0
Card          659103.0
Name: Net_Amount, dtype: float64

### Sales by Order Stutas

In [71]:
df.groupby('Order_Status')['Net_Amount'].sum().sort_values(ascending=False)

Order_Status
Returned     1110002.0
Delivered     997898.0
Cancelled     815124.0
Pending       804052.0
Name: Net_Amount, dtype: float64

### Monthly Sales

In [72]:
df.groupby('Order_Status')['Net_Amount'].sum().sort_values(ascending=False)

Order_Status
Returned     1110002.0
Delivered     997898.0
Cancelled     815124.0
Pending       804052.0
Name: Net_Amount, dtype: float64

### 16: Final Data Validation

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       380 non-null    object
 1   Order_Date     333 non-null    datetime64[ns]
 2   Customer_Name  380 non-null    object
 3   Email          380 non-null    object
 4   Phone          380 non-null    object
 5   City           380 non-null    object
 6   State          380 non-null    object
 7   Product        380 non-null    object
 8   Category       380 non-null    object
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    object
 13  Order_Status   380 non-null    object
 14  Delivery_Date  348 non-null    datetime64[ns]
 15  Sales          343 non-null    float64
 16  Net_Amount     343 non-null    float64
 17  Profit         343 non-null    float64
 18  Month          333 non-null    object
 19  Year           333 non-null    float64
 20  Weekday        333 non-null    object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 65.3+ KB

### 17: Export Clean Data

In [57]:
df.to_csv('Clean_Ecommerce.csv',index=False)

### Step 18: Import Data into MySQL

In [44]:
from sqlalchemy import create_engine 

engine = create_engine('mysql+pymysql://root:nakul123456@localhost/ecommerce')

In [45]:
# Export DataFrame to MySQL
df.to_sql(
    name='order',
    con=engine,
    if_exists='replace',
    index=False
)

380

In [46]:
df.shape

(380, 21)